#!/bin/sh /etc/rc.common

START=991
USE_PROCD=1
PROG=/usr/bin/serial-clock-sync
CONFFILE=/etc/serial-clock-sync.conf

start_service() {
  procd_open_instance
  procd_set_param command $PROG -f -c $CONFFILE
  procd_set_param file $CONFFILE
  procd_set_param respawn
  procd_close_instance
}
